[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeWinSize=16
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'w0rp/ale'

# Git

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# Ctags Gtags
[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    " Options
    let g:Gtags_Auto_Map = 0
    map <C-h> :Gtags -f %<CR>
    map <C-n> :cn<CR>
    map <C-p> :cp<CR>
'''

[[plugin]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
    let g:gen_tags#ctags_auto_gen = 1
    let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = '''
    " Prefix key
    nmap [denite] <Nop>
    map <C-j> [denite]
    " Keymap
    nmap <silent> [denite]<C-D> :Denite -buffer-name=gtags_completion gtags_completion<cr>
'''

# Snippets

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Airline

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    set laststatus=2
    set showtabline=2
    set t_Co=256
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode=1
    let g:airline#extensions#tabline#buffer_nr_show = 1
    let g:airline_powerline_fonts=1
    let g:airline_theme='onedark'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#Colors

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'joshdick/onedark.vim'
