[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
    let g:unite_enable_ignore_case=1
    let g:unite_enable_smart_case=1
    let g:unite_source_history_yank_enable=1
    let g:unite_source_file_mru_limit=200
    au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
    au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>

    nnoremap [unite] <Nop>
    nmap <Leader>f [unite]
    nnoremap [unite]u  :<C-u>Unite -no-split<Space>
    nnoremap <silent> [unite]f :<C-u>Unite<Space>file<CR>
    nnoremap <silent> [unite]g :<C-u>Unite<Space>grep<CR>
    nnoremap <silent> [unite]b :<C-u>Unite<Space>buffer<CR>
    nnoremap <silent> [unite]m :<C-u>Unite<Space>bookmark<CR>
    nnoremap <silent> [unite]a :<C-u>UniteBookmarkAdd<CR>
    nnoremap <silent> [unite]r :<C-u>Unite<Space>file_mru<CR>
    nnoremap <silent> [unite]p :<C-u>Unite<Space>file_point<CR>
    nnoremap <silent> [unite]h :<C-u>Unite<Space>history/yank<CR>
    nnoremap <silent> [unite]d :<C-u>Unite<Space>directory/new<CR>
    nnoremap <silent> [unite]n :<C-u>Unite<Space>file/new<CR>
    nnoremap <silent> [unite]v :<C-u>UniteWithBufferDir file<CR>
    nnoremap <silent> ,vr :UniteResume<CR>
    if executable('ag')
        let g:unite_source_grep_command = 'ag'
        let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
        let g:unite_source_grep_recursive_opt = ''
    endif
'''


[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
